import { describe, test, expect } from 'vitest';
import {
  calculatePlanExpiration,
  generateChildBirthdayHolidays,
  syncBirthdayWithChild,
  removeChildBirthday,
  syncBirthdaysWithChildren,
} from '../familyUtils';
import type { Child, BirthdayConfig } from '../../types';

describe('calculatePlanExpiration', () => {
  test('returns null for empty children array', () => {
    expect(calculatePlanExpiration([])).toBeNull();
  });

  test('calculates expiration for single child with default custodyEndAge', () => {
    const children: Child[] = [
      { id: '1', name: 'Alice', birthdate: '2015-03-15', custodyEndAge: 18 },
    ];
    expect(calculatePlanExpiration(children)).toBe('2033-03-15');
  });

  test('finds youngest child and calculates expiration based on them', () => {
    const children: Child[] = [
      { id: '1', name: 'Alice', birthdate: '2015-03-15', custodyEndAge: 18 },
      { id: '2', name: 'Bob', birthdate: '2018-07-20', custodyEndAge: 18 },
    ];
    // Bob is younger, so plan expires when he turns 18
    expect(calculatePlanExpiration(children)).toBe('2036-07-20');
  });

  test('respects different custodyEndAge values', () => {
    const children: Child[] = [
      { id: '1', name: 'Alice', birthdate: '2015-03-15', custodyEndAge: 19 },
    ];
    expect(calculatePlanExpiration(children)).toBe('2034-03-15');
  });

  test('handles leap year birthdate correctly', () => {
    const children: Child[] = [
      { id: '1', name: 'LeapYear', birthdate: '2016-02-29', custodyEndAge: 18 },
    ];
    // Feb 29, 2016 + 18 years -> should be Feb 28 or Mar 1 2034 (depending on implementation)
    // Since 2034 is not a leap year, JavaScript Date will roll to Mar 1
    expect(calculatePlanExpiration(children)).toBe('2034-03-01');
  });

  test('handles multiple children with different custodyEndAge', () => {
    const children: Child[] = [
      { id: '1', name: 'Older', birthdate: '2015-01-01', custodyEndAge: 21 },
      { id: '2', name: 'Younger', birthdate: '2020-06-15', custodyEndAge: 18 },
    ];
    // Older turns 21 on 2036-01-01
    // Younger turns 18 on 2038-06-15
    // Younger's expiration is later, so that's the plan expiration
    expect(calculatePlanExpiration(children)).toBe('2038-06-15');
  });

  test('handles children born in same year correctly', () => {
    const children: Child[] = [
      { id: '1', name: 'Twin1', birthdate: '2015-03-15', custodyEndAge: 18 },
      { id: '2', name: 'Twin2', birthdate: '2015-03-15', custodyEndAge: 18 },
    ];
    expect(calculatePlanExpiration(children)).toBe('2033-03-15');
  });
});

describe('generateChildBirthdayHolidays', () => {
  test('generates birthday for single child', () => {
    const children: Child[] = [
      { id: '1', name: 'Emma', birthdate: '2018-05-15', custodyEndAge: 18 },
    ];
    const birthdays = generateChildBirthdayHolidays(children);

    expect(birthdays).toHaveLength(1);
    expect(birthdays[0]).toEqual({
      id: 'birthday-1',
      name: "Emma's Birthday",
      type: 'child',
      month: 5,
      day: 15,
      defaultAssignment: 'alternate-odd-even',
      linkedChildId: '1',
      isAutoGenerated: true,
    });
  });

  test('generates birthdays for multiple children', () => {
    const children: Child[] = [
      { id: '1', name: 'Emma', birthdate: '2018-05-15', custodyEndAge: 18 },
      { id: '2', name: 'Jack', birthdate: '2020-12-25', custodyEndAge: 18 },
    ];
    const birthdays = generateChildBirthdayHolidays(children);

    expect(birthdays).toHaveLength(2);
    expect(birthdays[0].name).toBe("Emma's Birthday");
    expect(birthdays[0].month).toBe(5);
    expect(birthdays[0].day).toBe(15);
    expect(birthdays[1].name).toBe("Jack's Birthday");
    expect(birthdays[1].month).toBe(12);
    expect(birthdays[1].day).toBe(25);
  });

  test('handles twins with same birthday (creates separate entries)', () => {
    const children: Child[] = [
      { id: '1', name: 'Twin1', birthdate: '2018-05-15', custodyEndAge: 18 },
      { id: '2', name: 'Twin2', birthdate: '2018-05-15', custodyEndAge: 18 },
    ];
    const birthdays = generateChildBirthdayHolidays(children);

    expect(birthdays).toHaveLength(2);
    expect(birthdays[0].id).toBe('birthday-1');
    expect(birthdays[1].id).toBe('birthday-2');
    expect(birthdays[0].linkedChildId).toBe('1');
    expect(birthdays[1].linkedChildId).toBe('2');
  });

  test('skips children without birthdate', () => {
    const children: Child[] = [
      { id: '1', name: 'Emma', birthdate: '2018-05-15', custodyEndAge: 18 },
      { id: '2', name: 'NoDate', birthdate: '', custodyEndAge: 18 },
    ];
    const birthdays = generateChildBirthdayHolidays(children);

    expect(birthdays).toHaveLength(1);
    expect(birthdays[0].name).toBe("Emma's Birthday");
  });

  test('uses "Child" as fallback for empty name', () => {
    const children: Child[] = [
      { id: '1', name: '', birthdate: '2018-05-15', custodyEndAge: 18 },
    ];
    const birthdays = generateChildBirthdayHolidays(children);

    expect(birthdays[0].name).toBe("Child's Birthday");
  });
});

describe('syncBirthdayWithChild', () => {
  test('updates birthday name when child name changes', () => {
    const birthdays: BirthdayConfig[] = [
      {
        id: 'birthday-1',
        name: "Emma's Birthday",
        type: 'child',
        month: 5,
        day: 15,
        defaultAssignment: 'alternate-odd-even',
        linkedChildId: '1',
        isAutoGenerated: true,
      },
    ];
    const updatedChild: Child = { id: '1', name: 'Emily', birthdate: '2018-05-15', custodyEndAge: 18 };

    const result = syncBirthdayWithChild(birthdays, updatedChild);

    expect(result[0].name).toBe("Emily's Birthday");
    expect(result[0].month).toBe(5);
    expect(result[0].day).toBe(15);
  });

  test('updates birthday date when child birthdate changes', () => {
    const birthdays: BirthdayConfig[] = [
      {
        id: 'birthday-1',
        name: "Emma's Birthday",
        type: 'child',
        month: 5,
        day: 15,
        defaultAssignment: 'alternate-odd-even',
        linkedChildId: '1',
        isAutoGenerated: true,
      },
    ];
    const updatedChild: Child = { id: '1', name: 'Emma', birthdate: '2018-06-20', custodyEndAge: 18 };

    const result = syncBirthdayWithChild(birthdays, updatedChild);

    expect(result[0].name).toBe("Emma's Birthday");
    expect(result[0].month).toBe(6);
    expect(result[0].day).toBe(20);
  });

  test('does not modify unrelated birthdays', () => {
    const birthdays: BirthdayConfig[] = [
      {
        id: 'birthday-1',
        name: "Emma's Birthday",
        type: 'child',
        month: 5,
        day: 15,
        defaultAssignment: 'alternate-odd-even',
        linkedChildId: '1',
        isAutoGenerated: true,
      },
      {
        id: 'birthday-2',
        name: "Jack's Birthday",
        type: 'child',
        month: 12,
        day: 25,
        defaultAssignment: 'alternate-odd-even',
        linkedChildId: '2',
        isAutoGenerated: true,
      },
    ];
    const updatedChild: Child = { id: '1', name: 'Emily', birthdate: '2018-06-20', custodyEndAge: 18 };

    const result = syncBirthdayWithChild(birthdays, updatedChild);

    expect(result[0].name).toBe("Emily's Birthday");
    expect(result[1].name).toBe("Jack's Birthday");
    expect(result[1].month).toBe(12);
    expect(result[1].day).toBe(25);
  });

  test('preserves assignment when syncing', () => {
    const birthdays: BirthdayConfig[] = [
      {
        id: 'birthday-1',
        name: "Emma's Birthday",
        type: 'child',
        month: 5,
        day: 15,
        defaultAssignment: 'always-parent-a',
        linkedChildId: '1',
        isAutoGenerated: true,
      },
    ];
    const updatedChild: Child = { id: '1', name: 'Emily', birthdate: '2018-06-20', custodyEndAge: 18 };

    const result = syncBirthdayWithChild(birthdays, updatedChild);

    expect(result[0].defaultAssignment).toBe('always-parent-a');
  });
});

describe('removeChildBirthday', () => {
  test('removes birthday for specified child', () => {
    const birthdays: BirthdayConfig[] = [
      {
        id: 'birthday-1',
        name: "Emma's Birthday",
        type: 'child',
        month: 5,
        day: 15,
        defaultAssignment: 'alternate-odd-even',
        linkedChildId: '1',
        isAutoGenerated: true,
      },
      {
        id: 'birthday-2',
        name: "Jack's Birthday",
        type: 'child',
        month: 12,
        day: 25,
        defaultAssignment: 'alternate-odd-even',
        linkedChildId: '2',
        isAutoGenerated: true,
      },
    ];

    const result = removeChildBirthday(birthdays, '1');

    expect(result).toHaveLength(1);
    expect(result[0].id).toBe('birthday-2');
  });

  test('returns same array when child ID not found', () => {
    const birthdays: BirthdayConfig[] = [
      {
        id: 'birthday-1',
        name: "Emma's Birthday",
        type: 'child',
        month: 5,
        day: 15,
        defaultAssignment: 'alternate-odd-even',
        linkedChildId: '1',
        isAutoGenerated: true,
      },
    ];

    const result = removeChildBirthday(birthdays, 'non-existent');

    expect(result).toHaveLength(1);
    expect(result[0].id).toBe('birthday-1');
  });

  test('preserves manual birthdays without linkedChildId', () => {
    const birthdays: BirthdayConfig[] = [
      {
        id: 'birthday-1',
        name: "Emma's Birthday",
        type: 'child',
        month: 5,
        day: 15,
        defaultAssignment: 'alternate-odd-even',
        linkedChildId: '1',
        isAutoGenerated: true,
      },
      {
        id: 'manual-birthday',
        name: 'Manual Birthday',
        type: 'child',
        month: 3,
        day: 10,
        defaultAssignment: 'alternate-odd-even',
      },
    ];

    const result = removeChildBirthday(birthdays, '1');

    expect(result).toHaveLength(1);
    expect(result[0].id).toBe('manual-birthday');
  });
});

describe('syncBirthdaysWithChildren', () => {
  test('creates birthday for new child', () => {
    const birthdays: BirthdayConfig[] = [];
    const children: Child[] = [
      { id: '1', name: 'Emma', birthdate: '2018-05-15', custodyEndAge: 18 },
    ];

    const result = syncBirthdaysWithChildren(birthdays, children);

    expect(result).toHaveLength(1);
    expect(result[0].name).toBe("Emma's Birthday");
    expect(result[0].linkedChildId).toBe('1');
    expect(result[0].isAutoGenerated).toBe(true);
  });

  test('removes birthday when child is removed', () => {
    const birthdays: BirthdayConfig[] = [
      {
        id: 'birthday-1',
        name: "Emma's Birthday",
        type: 'child',
        month: 5,
        day: 15,
        defaultAssignment: 'alternate-odd-even',
        linkedChildId: '1',
        isAutoGenerated: true,
      },
    ];
    const children: Child[] = []; // Child removed

    const result = syncBirthdaysWithChildren(birthdays, children);

    expect(result).toHaveLength(0);
  });

  test('updates existing birthday when child info changes', () => {
    const birthdays: BirthdayConfig[] = [
      {
        id: 'birthday-1',
        name: "Emma's Birthday",
        type: 'child',
        month: 5,
        day: 15,
        defaultAssignment: 'always-parent-a', // Custom assignment
        linkedChildId: '1',
        isAutoGenerated: true,
      },
    ];
    const children: Child[] = [
      { id: '1', name: 'Emily', birthdate: '2018-06-20', custodyEndAge: 18 },
    ];

    const result = syncBirthdaysWithChildren(birthdays, children);

    expect(result).toHaveLength(1);
    expect(result[0].name).toBe("Emily's Birthday");
    expect(result[0].month).toBe(6);
    expect(result[0].day).toBe(20);
    expect(result[0].defaultAssignment).toBe('always-parent-a'); // Preserved
  });

  test('preserves manual birthdays when syncing', () => {
    const birthdays: BirthdayConfig[] = [
      {
        id: 'manual-birthday',
        name: 'Manual Birthday',
        type: 'child',
        month: 3,
        day: 10,
        defaultAssignment: 'alternate-odd-even',
      },
    ];
    const children: Child[] = [
      { id: '1', name: 'Emma', birthdate: '2018-05-15', custodyEndAge: 18 },
    ];

    const result = syncBirthdaysWithChildren(birthdays, children);

    expect(result).toHaveLength(2);
    expect(result.find((b) => b.id === 'manual-birthday')).toBeDefined();
    expect(result.find((b) => b.linkedChildId === '1')).toBeDefined();
  });

  test('preserves parent birthdays when syncing', () => {
    const birthdays: BirthdayConfig[] = [
      {
        id: 'parent-a-birthday',
        name: "Parent A's Birthday",
        type: 'parent-a',
        month: 1,
        day: 15,
        defaultAssignment: 'always-parent-a',
      },
    ];
    const children: Child[] = [
      { id: '1', name: 'Emma', birthdate: '2018-05-15', custodyEndAge: 18 },
    ];

    const result = syncBirthdaysWithChildren(birthdays, children);

    expect(result).toHaveLength(2);
    expect(result.find((b) => b.type === 'parent-a')).toBeDefined();
  });

  test('handles complex scenario with multiple changes', () => {
    const birthdays: BirthdayConfig[] = [
      {
        id: 'birthday-1',
        name: "Emma's Birthday",
        type: 'child',
        month: 5,
        day: 15,
        defaultAssignment: 'alternate-odd-even',
        linkedChildId: '1',
        isAutoGenerated: true,
      },
      {
        id: 'birthday-2',
        name: "Jack's Birthday",
        type: 'child',
        month: 12,
        day: 25,
        defaultAssignment: 'alternate-odd-even',
        linkedChildId: '2',
        isAutoGenerated: true,
      },
      {
        id: 'parent-a-birthday',
        name: "Parent A's Birthday",
        type: 'parent-a',
        month: 1,
        day: 15,
        defaultAssignment: 'always-parent-a',
      },
    ];
    const children: Child[] = [
      { id: '1', name: 'Emily', birthdate: '2018-06-20', custodyEndAge: 18 }, // Emma renamed & date changed
      // Jack removed
      { id: '3', name: 'Sophie', birthdate: '2022-08-10', custodyEndAge: 18 }, // New child
    ];

    const result = syncBirthdaysWithChildren(birthdays, children);

    expect(result).toHaveLength(3);

    // Parent A birthday preserved
    const parentBirthday = result.find((b) => b.type === 'parent-a');
    expect(parentBirthday).toBeDefined();

    // Emma updated to Emily
    const emilyBirthday = result.find((b) => b.linkedChildId === '1');
    expect(emilyBirthday?.name).toBe("Emily's Birthday");
    expect(emilyBirthday?.month).toBe(6);
    expect(emilyBirthday?.day).toBe(20);

    // Jack removed
    const jackBirthday = result.find((b) => b.linkedChildId === '2');
    expect(jackBirthday).toBeUndefined();

    // Sophie added
    const sophieBirthday = result.find((b) => b.linkedChildId === '3');
    expect(sophieBirthday?.name).toBe("Sophie's Birthday");
    expect(sophieBirthday?.month).toBe(8);
    expect(sophieBirthday?.day).toBe(10);
  });

  test('does not create duplicate birthday for child that already has one', () => {
    const birthdays: BirthdayConfig[] = [
      {
        id: 'birthday-1',
        name: "Emma's Birthday",
        type: 'child',
        month: 5,
        day: 15,
        defaultAssignment: 'alternate-odd-even',
        linkedChildId: '1',
        isAutoGenerated: true,
      },
    ];
    const children: Child[] = [
      { id: '1', name: 'Emma', birthdate: '2018-05-15', custodyEndAge: 18 },
    ];

    // Call sync twice
    const result1 = syncBirthdaysWithChildren(birthdays, children);
    const result2 = syncBirthdaysWithChildren(result1, children);

    expect(result2).toHaveLength(1);
  });
});
