name: Technical Debt
description: Document technical debt that needs to be addressed
title: '[Tech Debt]: '
labels: ['technical-debt']
body:
  - type: markdown
    attributes:
      value: |
        Use this template to document technical debt items that need attention.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the technical debt item.
      placeholder: A clear description of the technical debt.
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the impact of this technical debt on the codebase or team?
      placeholder: |
        - Performance issues
        - Maintainability concerns
        - Security implications
        - Developer experience
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: Location in Codebase
      description: Where is this technical debt located?
      placeholder: |
        - File(s): src/example.ts
        - Module(s): authentication
        - Component(s): UserService
    validations:
      required: false
  - type: textarea
    id: proposed-fix
    attributes:
      label: Proposed Solution
      description: How should this technical debt be addressed?
    validations:
      required: false
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this technical debt?
      options:
        - Low - Minor inconvenience
        - Medium - Affects productivity
        - High - Significant risk or blocker
        - Critical - Immediate attention required
    validations:
      required: true
  - type: textarea
    id: effort
    attributes:
      label: Estimated Effort
      description: How much effort is required to address this?
      placeholder: |
        - Small (< 1 day)
        - Medium (1-3 days)
        - Large (1 week)
        - Extra Large (> 1 week)
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the technical debt here.
    validations:
      required: false
